services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: short-link-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    container_name: short-link-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: short-link-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: short-link
      POSTGRES_USER: short-link
      POSTGRES_PASSWORD: short-link
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U short-link -d short-link"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
